servers:
  0:
    host: 127.0.0.1
    port: 17701
    device: 1
  1:
    host: 127.0.0.1
    port: 17702
    device: 1
  2:
    host: 127.0.0.1
    port: 17703
    device: 1
  3:
    host: 127.0.0.1
    port: 17704
    device: 1
  4:
    host: 127.0.0.1
    port: 17705
    device: 2
  5:
    host: 127.0.0.1
    port: 17706
    device: 2
  6:
    host: 127.0.0.1
    port: 17707
    device: 2
  7:
    host: 127.0.0.1
    port: 17708
    device: 2

